
BC_WO_TMS_TASK


select Create_Date,Last_Modified_By,Modified_Date,CAST(Notes as nvarchar(max)) as Notes,Summary,Task_ID,EffortTrackingTotalTimeSpentMi,EffortTrackingTotalTimeSpentHo,Scheduled_Start_Date,Scheduled_End_Date,Actual_Start_Date,Actual_End_Date,Assign_Time,Activate_Time,TimeOutValue,Expected_Time_Out,Duration_In_Minutes,InstanceId,RootRequestInstanceID,RootRequestName,TaskType,Status,Priority,Notify_Assignee,REGION,COMPANY,SITE_GROUP,SITE,Location_Company,Submitter,TaskName, First_Name,Middle_Name,Last_Name,Phone_Number,Organization,Department,Support_Organization,Support_Group_Name,Customer_Company,Customer_First_Name,Customer_Middle_Name,Customer_Last_Name,Customer_Phone_Number,Customer_Organization,Customer_Department,Service_Cat_Tier_1,Service_Cat_Tier_2,Service_Cat_Tier_3,Product_Cat_Tier_1,Product_Cat_Tier_2,Product_Cat_Tier_3,Product_Name,Product_Model_Version,Manufacturer,Support_Company,Assignee_Organization,Assignee_Group,Assignee      from TMS_TASK
